package es.udc.fic.vvs.contenido;

import java.util.ArrayList;
import java.util.List;

import junit.framework.TestCase;

/**
 * The class <code>CancionTest</code> contains tests for the class {@link
 * <code>Cancion</code>}
 *
 * @pattern JUnit Test Case
 *
 * @generatedBy CodePro at 15/11/15 0:17
 *
 * @author alejandro
 *
 * @version $Revision$
 */
public class TestCancion extends TestCase {

	/**
	 * Construct new test instance
	 *
	 * @param name the test name
	 */
	public TestCancion(String name) {
		super(name);
	}

	/**
	 * Run the String obtenerTitulo() method test
	 */
	public void testObtenerTitulo() {
		Cancion cancion = new Cancion("Cancion", 5.5);
		assertEquals(cancion.obtenerTitulo(), "Cancion");
	}
	
	/**
	 * Run the double obtenerDuracion() method test
	 */
	public void testObtenerDuracion() {
		Cancion cancion = new Cancion("Cancion", 5.5);
		assertEquals(cancion.obtenerDuracion(), 5.5);
	}
	
	/**
	 * Run the List<Contenido> obtenerListaReproduccion() method test
	 */
	public void testObtenerListaReproduccion() {
		Cancion cancion = new Cancion("Cancion", 5.5);
		List<Contenido> listaReproduccion = new ArrayList<Contenido>();
		listaReproduccion.add(cancion);
		assertEquals(cancion.obtenerListaReproduccion(), listaReproduccion);
	}

	/**
	 * Run the List<Contenido> buscar(String) method test
	 */
	public void testBuscar() {
		Cancion cancion = new Cancion("Cancion", 5.5);
		List<Contenido> listaReproduccion = new ArrayList<Contenido>();
		listaReproduccion.add(cancion);
		assertEquals(cancion.buscar("Cancion"), listaReproduccion);
		assertEquals(cancion.buscar("Canc"), listaReproduccion);
		assertTrue(cancion.buscar("FALLO").size() == 0);
	}


}

/*$CPS$ This comment was generated by CodePro. Do not edit it.
 * patternId = com.instantiations.assist.eclipse.pattern.testCasePattern
 * strategyId = com.instantiations.assist.eclipse.pattern.testCasePattern.junitTestCase
 * additionalTestNames = 
 * assertTrue = false
 * callTestMethod = true
 * createMain = false
 * createSetUp = false
 * createTearDown = false
 * createTestFixture = false
 * createTestStubs = true
 * methods = 
 * package = es.udc.fic.vvs.contenido
 * package.sourceFolder = practica-vvs/src/test/java
 * superclassType = junit.framework.TestCase
 * testCase = CancionTest
 * testClassType = es.udc.fic.vvs.contenido.Cancion
 */